name: CI_Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies and Run Tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

# Define CD_Pipeline to run only when CI_Pipeline is completed successfully
CD_Pipeline:
  runs-on: ubuntu-latest
  needs: build
  if: github.event_name == 'workflow_run' && github.event.workflow == 'CI_Pipeline' && github.event.workflow_run.conclusion == 'success'
  steps:
    - name: Deployment Step
      run: |
        echo "Deployment triggered after successful CI Pipeline completion"
        # Add deployment steps here
        
