name: CI-Pipeline

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Database Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        run: |  
          python manage.py test
