name: CI_Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies and Run Tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

# Define CD_Pipeline workflow triggered after CI_Pipeline completes
CD_Pipeline:
  needs: CI_Pipeline
  types: [workflow_run]
  runs-on: ubuntu-latest
  steps:
    - name: Trigger CD pipeline
      run: echo "Triggering CD pipeline after CI completion"
      # Add steps here to perform actions after successful CI completion
